.\" (c) 2006, Quest Software, Inc. All rights reserved.
.TH DNSUPDATE 8
.SH NAME
dnsupdate \- updates a DNS entry in Active Directory
.SH SYNOPSIS
.B dnsupdate
[\-INrvV]
.RI [\-a\  auth-domain ]
.RI [\-d\  domain ]
.RI [\-h\  hostname ]
.RI [\-o\  option = value ]
.RI [\-s\  nameserver ]
.RI [\-t\  ttl ]
.I ip-addr
.SH DESCRIPTION
The
.B dnsupdate
utility authenticates to an Active Directory DNS server
as a computer object, and updates its IP address.
.PP
The
.B dnsupdate
utility should be run whenever the primary interface's IP address is configured
(e.g. from a DHCP hook).
.SS OPTIONS
.TP
.RI \-a\  auth-domain
specifies the authoritative domain to use when updating.
The default is to determine the authoritative domain automatically.
.TP
.RI \-d\  domain
specifies the Active Directory domain (realm) in which to authenticate.
The default is to use the currently joined domain.
.TP
.RI \-h\  hostname
specifies the fully qualified hostname to use when updating the DNS entry.
The default is to use the DNS hostname associated with the computer object
corresponding to the system host principal.
.TP
\-I
use the IETF's
.I gss-tsig
algorithm name (see RFC 3654).
The default is to use
.I gss.microsoft.com
which is understood by Active Directory.
.TP
\-N
disable GSS authentication
.TP
\-r
Update the reverse PTR record instead.
The reverse name in in-addr.arpa is computed from the
.I ipaddr
and a PTR record update is attempted.
.TP
.RI \-o\  option = value
Overrides an option setting.
.TP
.RI \-s\  nameserver
specifies the nameserver host to send the dynamic DNS update requests to.
The default is to try all domain controllers, using the nearest first.
.TP
.RI \-t\  ttl
specifies the name's DNS cache lifetime, in seconds.
If not provided, defaults to one hour.
This value is not the same as the DHCP lease time.
If specified as zero, the DNS entry will be deleted instead of updated.
.TP
\-v
increases the level of verbosity
.TP
\-V
displays version information, then exits.
.SS OPTIONS
Options are read from
/etc/opt/quest/dnsupdate.conf
before argument processing begins.
.TP
.RI UpdateSecurityLevel= integer
A value of zero (default) indicates that an un-authenticated updated is
tried first, and then a secure update only if the first fails.
A value of 16 enables only un-authenticated updates.
A value of 256 enables only authenticated updates.
.TP
.TI DefaultRegistrationTTL= seconds
The default TTL used 
.SS "EXIT STATUS"
The
.B dnsupdate
utility exits with status 0 if the update succeeded.
.SH "SEE ALSO"
vastool(1),
dnsupdate-install-hooks(8),
.I http://rc.quest.com/topics/ddns/
.SH AUTHORS
David Leonard, Quest Software, Inc.
