.\" (c) 2008, Quest Software, Inc. All rights reserved.
.TH DNSUPDATE-INSTALL-HOOKS 8
.SH NAME
dnsupdate-install-hooks \- installs dnsupdate(8) into DHCP client hooks
.SH SYNOPSIS
.B dnsupdate-install-hooks
[\-irqh]
.I platform
.SH DESCRIPTION
The
.B dnsupdate-install-hooks
utility manages
dnsupdate(8)'s
hook into the local system's DHCP client.
.PP
The
.B dnsupdate-install-hooks
script is run automatically when the quest-dnsupdate package is 
installed or uninstalled.
.SS OPTIONS
.TP
\-i
installs the hook
.TP
\-r
removes the hook
.TP
\-h
displays a help message
.TP
\-q
quiet mode: verbose messages are suppressed
.TP
.I platform
selects the DHCP client software.
One of:
linux
aix
hpux
solaris
macos.
.PP
Note that running this script with the
\-i
option multiple times may result in dnsupdate being hooked multiple times,
and that is generally not what you want.
.SH "SEE ALSO"
dnsupate(8),
.I http://rc.quest.com/topics/ddns/
.SH AUTHORS
Quest Software, Inc.
