.\" (c) 2008, Quest Software, Inc. All rights reserved.
.TH DNSUPDATE-INSTALL-HOOKS 8
.SH NAME
dnsupdate-install-hooks \- installs dnsupdate(8) into DHCP client hooks
.SH SYNOPSIS
.B dnsupdate-install-hooks
[\-hiqrt]
.I platform
.SH DESCRIPTION
The
.B dnsupdate-install-hooks
utility is called by the packaging system to manage
dnsupdate(8)'s
hook into the local system's DHCP client.
.PP
This script can be run by an administrator, but normally it
is run automatically by the packaging system when the dnsupdate package is 
installed, upgraded or removed.
.SS OPTIONS
.TP
\-h
displays a help message
.TP
\-i
installs the hook
.TP
\-q
quiet mode: verbose messages are suppressed
.TP
\-r
removes the hook
.TP
\-t
tests to see if the hook appears to have already been installed
.TP
.I platform
selects the DHCP client software.
One of:
aix, hpux, solaris, macos, linux, dhclient, dhcpcd, or odhcpcd.
Note that 'linux' auto-detects dhclient, dhcpcd or odhcpcd.
.PP
Note that running this script with the
\-i
option multiple times may result in dnsupdate being hooked multiple times,
and that is generally not what you want.
.SH "SEE ALSO"
dnsupate(8),
.I http://rc.quest.com/topics/ddns/
.SH AUTHORS
Quest Software, Inc.
