.\" (c) 2006, Quest Software, Inc. All rights reserved.
.TH DNSUPDATE 8
.SH NAME
dnsupdate \- update an DNS entry in Active Directory
.SH SYNOPSIS
.B dnsupdate
.RI [\-d\  domain ]
.RI [\-h\  hostname ]
.RI [\-s\  nameserver ]
.RI [\-t\  ttl ]
[\-v]
.I ip-addr
.SH DESCRIPTION
The
.B dnsupdate
utility authenticates to an Active Directory DNS server
as a computer object, and updates its IP address.
.PP
The
.B dnsupdate
utility should be run whenever the primary interface's IP address is configured
(e.g. from a DHCP hook).
.SS OPTIONS
.TP
.RI \-d\  domain
the Active Directory domain (realm) in which to authenticate,
defaults to the currently joined domain
.TP
.RI \-h\  hostname
the fully qualified hostname entry to update,
defaults to the DNS hostname associated with the current AD computer object
.TP
.RI \-s\  nameserver
the nameserver to perform the dynamic DNS update operation on,
defaults to the nearest domain controller with automatic fallback
.TP
.RI \-t\  ttl
the cache lifetime in seconds to store with the new DNS entry,
defaults to one hour
.TP
\-v
increases the level of verbosity
.SS "EXIT STATUS"
The
.B dnsupdate
tool exits with status 0 only if the update operation was successful.
.SH "SEE ALSO"
vastool(1),
.I http://rc.vintela.com/topics/ddns/
.SH AUTHORS
David Leonard, Quest Software, Inc.
