.\" (c) 2006, Quest Software, Inc. All rights reserved.
.TH IPWATCHD 8
.SH NAME
ipwatchd \- runs a program when the primary IP address changes
.SH SYNOPSIS
.B ipwatchd
[\-d]
.RI [ ChangeProgram ]
.SH DESCRIPTION
The
.B ipwatchd
daemon watches MacOS X's dynamic System Configuration state for interface
address changes, and runs the given program with the new IP address.
.PP
The
.B ipwatchd
utility is intended to be started by the
launchd(8)
daemon.
.SS OPTIONS
.TP
.RI \-d
This option
enables debug (verbose) mode
.TP
.I ChangeProgram
This argument specifies the program to execute. 
The executed program is given the new IP address as its first argument.
.PP
If
.B ipwatchd
is run by
.B launchd
and no
.I ChangeProgram
argument is provided, then
.B ipwatchd
will look for and use a string-valued configuration key named ChangeProgram
passed to it by
.BR ipwatchd .
.SH FILES
.I /Library/LaunchDaemons/com.quest.rc.ipwatchd.plist
.SH "SEE ALSO"
dnsupdate(8),
launchd(8),
.I http://rc.vintela.com/topics/ddns/
.SH AUTHORS
David Leonard, Quest Software, Inc.
